[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "SNAT"
version = "0.1.1"
description = "A Python library for evaluating node importance in social networks using H-index and its derivatives"
readme = "README.md"
authors = [{name = "Xiangbin Yan", email = " xbyan@ustb.edu.cn"},
           {name = "Zhai Li", email = "zl6168@sina.com"},
           {name = "Jiahua Jin", email = "jinjiahua@ustb.edu.cn"},
           {name = "Wei Gu", email = "guwei@ustb.edu.cn"}]

license = {text = "MIT"}
classifiers = [
    "Development Status :: Stable release",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
requires-python = ">=3.7"
dependencies = [
    "pandas>=1.3.0",
    "numpy>=1.19.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "pytest-cov>=2.0",
    "black>=21.0",
    "flake8>=3.8"
]

[project.urls]
Homepage = "https://github.com/jiahuaking/SNAT.git"
